pipeline {
    agent { label 'built-in' }

    environment {
        git_branch = 'main'
        git_url = 'https://github.com/pavankumarch1219/Amazon.git'
    }

    stages {

        stage('Clone') {
            steps {
                git branch: "${git_branch}", url: "${git_url}"
            }
        }

        stage('Clean') {
            steps {
                dir('Amazon') {
                    sh 'mvn clean'
                }
            }
        }

        stage('Compile') {
            steps {
                dir('Amazon') {
                    sh 'mvn compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Amazon') {
                    sh 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('Amazon') {
                    sh 'mvn package'
                }
            }
        }

        stage('Install') {
            steps {
                dir('Amazon') {
                    sh 'mvn clean install'
                }
            }
        }
    }

    post {

        success {
            echo "Build completed successfully!"

            mail to: 'maruthi.bg6@gmail.com,maruthi.abc.reports@gmail.com,pavankumarch29@gmail.com,pavan.abc.reports@gmail.com',
                 subject: "BUILD SUCCESS: ${env.JOB_NAME}",
                 body: "The Jenkins job '${env.JOB_NAME}' completed SUCCESSFULLY.\n\nConsole output:\n${env.BUILD_URL}"
        }

        failure {
            echo "Build failed."

            mail to: 'pavan.abc.reports@gmail.com',
                 subject: "BUILD FAILURE: ${env.JOB_NAME}",
                 body: "The Jenkins job '${env.JOB_NAME}' has FAILED.\n\nCheck console output:\n${env.BUILD_URL}"
        }

        unstable {
            echo "Build is unstable."

            mail to: 'pavan.abc.reports@gmail.com',
                 subject: "BUILD UNSTABLE: ${env.JOB_NAME}",
                 body: "The Jenkins job '${env.JOB_NAME}' is UNSTABLE.\n\nCheck console output:\n${env.BUILD_URL}"
        }

        aborted {
            echo "Build aborted."

            mail to: 'pavan.abc.reports@gmail.com',
                 subject: "BUILD ABORTED: ${env.JOB_NAME}",
                 body: "The Jenkins job '${env.JOB_NAME}' was aborted.\n\nConsole output:\n${env.BUILD_URL}"
        }

        always {
            echo "Pipeline finished."
        }
    }
} 
