pipeline {
    agent any

    stages {

        stage('Clone Project') {
            steps {
                git branch: 'main', url: 'https://github.com/pavankumarch1219/Amazon.git'
            }
        }

        stage('Clean') {
            steps {
                dir('Amazon') {
                    sh 'mvn clean'
                }
            }
        }

        stage('Compile') {
            steps {
                dir('Amazon') {
                    sh 'mvn compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Amazon') {
                    sh 'mvn test'
                }
            }
        }

        stage('Build') {
            steps {
                dir('Amazon') {
                    sh 'mvn clean install'
                }
            }
        }
    }

post {
    success {
        emailext(
            to: 'pavan.abc.reports@gmail.com',
            subject: 'SUCCESS: AMAZON Job',
            body: "Build completed successfully.\n${env.BUILD_URL}"
        )
    }
    failure {
        emailext(
            to: 'pavan.abc.reports@gmail.com',
            subject: 'FAILED: AMAZON Job',
            body: "Build failed.\nCheck logs: ${env.BUILD_URL}"
        )
    }
}

    }

